[build]
  publish = "public"
  command = "hugo --minify --buildFuture"

[build.environment]
  HUGO_VERSION = "0.152.2"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_ENV = "preview"
